examples/aws/main.tf, examples/azure/main.tf, examples/gcp/main.tf, examples/openstack/main.tf, examples/ovh/main.tf
Added quotes around the email field in order to avoid confusion. (Or maybe it's just me!)
=> Added quotes around the emails in main.tf (examples)

dns/gcloud/README.md, dns/gcloud/acme.tf, dns/gcloud/dns.tf, dns/gcloud/key2fp.py, dns/gcloud/versions.tf, examples/openstack/main.tf
New PR that is based off of master. Adds support for using Google Cloud for dns and for Lets Encrypt DNS challenges.
=> Adding support for publishing dns records

azure/infrastructure.tf
Refactoring of infrastructure.tf to conform to new syntax and standards for the updated provider major version.
=> Update infrastructure.tf for Terraform Azure Provider 2.0

aws/README.md, azure/README.md, gcp/README.md, ovh/README.md
=> Typo in some READMEs

CHANGELOG, common/data.tf, common/outputs.tf, common/variables.tf, dns/acme/main.tf, dns/cloudflare/main.tf, dns/cloudflare/variables.tf, dns/gcloud/main.tf, dns/gcloud/variables.tf, docs/README.md, examples/aws/main.tf, examples/azure/main.tf, examples/gcp/main.tf, examples/openstack/main.tf, examples/ovh/main.tf
The keypair is then used to upload the files with Terraform file-provisioner.
=> Add ability to generate an ssh keypair

docs/README.md
- remove word
- fix grammar
- fix spelling (and re-shape sentence a bit)
=> Fix 3 typos docs/README.md

azure/infrastructure.tf, docs/README.md
=> Allow configuration of image using image_id in Azure

aws/aws.tf, azure/azure.tf, common/data.tf, gcp/gcp.tf, openstack/keystone.py, openstack/openstack.tf, ovh/ovh.tf
Allow to change data source in hieradata based on the cloud used and the region
=> Add a cloud provider and region facts to puppet

dns/txt/main.tf, dns/txt/variables.tf, docs/README.md
=> Add txt dns module and docs

dns/gcloud/main.tf
Closes #166.
I opened this PR as it felt like a viable resolution to #166 and if not a sensible way to discuss resolving the issue more concretely.
=> Fix for gcloud dns: update dns_provider and dns_provider_config

common/outputs.tf
=> Change output public_ip to be a map instead of an array

docs/README.md
And added a paragraph on retrieving the admin password.
=> Fixed documentation for FreeIP admin

aws/infrastructure.tf, azure/infrastructure.tf, docs/README.md, gcp/infrastructure.tf, openstack/infrastructure.tf
Allow overriding var.image value for some or all instance types.
Closes #202
=> Add `image` optional instance attribute

dns/record_generator/main.tf
This is to support the portal in this PR https://github.com/ComputeCanada/puppet-magic_castle/pull/211
=> Adding "portal" vhost entry in DNS

dns/record_generator/main.tf
Reverts ComputeCanada/magic_castle#220
=> Revert "Fix issue #214"

openstack/infrastructure.tf
This potentially does not work well with autoscaling.
=> Remove possibility of openstack soft deleting an instance

common/variables.tf, docs/README.md
Review character limits in documentation too
Fix #255 and #257
=> Improve cluster_name, domain and instance prefix validation

aws/infrastructure.tf, azure/infrastructure.tf, common/configuration/main.tf, docs/README.md, docs/design.md, gcp/infrastructure.tf, openstack/infrastructure.tf
=> Move volumes in instance specs

azure/network.tf
=> Fix issue #313

azure/network.tf
=> Define a value for sku in azurerm_public_ip

common/configuration/puppet.yaml
=> Make tf user a system user

common/configuration/main.tf
Otherwise, puppet risks erroring when applying the catalog with this message:
```
Failed to apply catalog: Parameter key failed on Ssh_authorized_key[centos_0]: Key must not contain whitespace:
```
=> Make sure ssh keys do not have whitespace prefix or suffix

aws/infrastructure.tf
Limit the choices to only what is possible given the selected instance types instead of all AZ available.
=> Reduce choices of availablity zones in AWS

.github/workflows/trivy_scan.yaml, .trivyignore, docs/README.md
=> Add Trivy misconfiguration scan of Terraform code
