docs/README.md, openstack/network.tf, openstack/openstack.tf
This is required on Openstack when multiple subnets are in the same network. Mostly when both IPv4 and IPv6 is available.
=> Adding a variable to force to use a specific subnet with Openstack

azure/azure.tf, azure/infrastructure.tf, docs/README.md
Allow users to specify a previously created resource group and if none is defined create a new resource group.
Resolves Issue #72
=> Allow Azure resource group reuse

examples/aws/main.tf, examples/azure/main.tf, examples/gcp/main.tf, examples/openstack/main.tf, examples/ovh/main.tf
setsubtract, introduced in terraform 0.12.21
Otherwise, the following error is observed : 
```
Error: Call to unknown function
on openstack/data.tf line 12, in locals:
12:             for key in setsubtract(keys(node), ["prefix", "count"]):
There is no function named "setsubtract".
```
=> bumped minimum requirement of terraform due to the use of function 

docs/README.md, docs/developers.md, docs/globus.md
PyCharm seems to struggle when displaying non-indented code blocks within a numbered list. This seems to be fixed when adding 4 spaces at the beginning of each code block in the list. This problem does not arise when displaying the Markdown documentation on GitHub though.
I also fixed a few typos.
=> Fixed a few typos and indentation errors in documentation

examples/gcp/main.tf
If unchanged root_disk_size of 10GB causes this error:
```
Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.disks[0].initializeParams.diskSizeGb': '10'. Requested disk size cannot be smaller than the image size (20 GB), invalid
on gcp/infrastructure.tf line 86, in resource "google_compute_instance" "mgmt":
86: resource "google_compute_instance" "mgmt" {
```
=> Changed root_disk_size from 10GB to 20GB for GCP

aws/infrastructure.tf, azure/infrastructure.tf, cloud-init/puppetmaster.yaml, common/data.tf, common/variables.tf, docs/README.md, gcp/infrastructure.tf, openstack/infrastructure.tf
This allows modifications of the number of guest accounts, the guest account password and the hieradata string without requiring a rebuild of mgmt1.
=> Upload hieradata yaml files with Terraform file provisioner

docs/README.md
On the management node, the path is `/mnt/home`.
```
[centos@mgmt1 ~]$ ls /home/
[centos@mgmt1 ~]$ ls /mnt/home/
user01  ....
```
=> Fix path in docs. On mgmt1 `/home` is empty.

examples/aws/main.tf
The AWS example should use the AWS private SSH key, not the OpenStack one
=> Use AWS private SSH key in example

cloud-init/puppetmaster.yaml, common/data.tf, common/variables.tf, docs/README.md
This relies on https://github.com/ComputeCanada/puppet-magic_castle/pull/77 and requires the generation of a file based on the template in `site/profile/facts.d/terraform_facts.yaml.tmpl` there.
=> Add a variable to trigger different software stacks

docs/README.md
The name of the configuration variable `profile::base::email` doesn't match with the one documented here: https://github.com/ComputeCanada/puppet-magic_castle/#profilebase (`profile::base::admin_email`).
_1 virtual beer has been added to lefreud's account._
=> Fixed puppet hieradata documentation typo

docs/README.md
- One internal link fixed.
- Generic introduction for the password replacement procedure
- Changed one Bash comment into a `grep` command
=> Straightforward password replacement procedure

common/outputs.tf, examples/aws/main.tf, examples/azure/main.tf, examples/gcp/main.tf, examples/openstack/main.tf, examples/ovh/main.tf
It wasn't clear to me that the administrator username for freeipa is not `sudoer_username` but `"admin"` and took me a while to figure out when I first tried.
=> Notify about what the freeipa admin username is

docs/README.md
I went ahead and checked all links in this markdown file, and this was the only one I found that was broken.
=> Fix typo and broken link in docs

aws/infrastructure.tf, azure/infrastructure.tf, common/cluster_config/main.tf, common/cluster_config/terraform_data.yaml, common/cluster_config/variables.tf, common/instance_config/main.tf, common/instance_config/outputs.tf, common/outputs.tf, docs/README.md, gcp/infrastructure.tf, openstack/infrastructure.tf
Address issue #174 where users who would like to add public ssh keys to the sudoer account have to destroy and re-create all instances, which is counter-intuitive and inefficient.
=> Add SSH public keys to terraform_data and ignore changes to user_data for instances.

docs/README.md
The command
```
$ terraform taint 'module.openstack.openstack_compute_instance_v2.login[0]'
```
found in the documentation throws 
```
╷
│ Error: No such resource instance
│ 
│ There is no resource instance in the state with the address module.openstack.openstack_compute_instance_v2.login[0]. If the resource configuration has
│ just been added, you must run "terraform apply" once to create the corresponding instance(s) before they can be tainted.
╵
```
(Hope it qualifies for #33 :grin:)
=> Fix taint command example

README.md, aws/infrastructure.tf, docs/README.md
Our spot instances on Amazon are not actually persistent, when they die they do not restart. It was hard to discover but I found this documented somewhere:
```
* For <a>RunInstances</a>, persistent Spot Instance requests are only supported when
* <b>InstanceInterruptionBehavior</b> is set to either <code>hibernate</code> or <code>stop</code>.
* </p>
```
By default (and in our case) `InstanceInterruptionBehavior` is set to terminate , we need to change this to `stop`. I noticed as I left a spot cluster running over the weekend, and when I came back all the compute nodes had died.
=> Ensure AWS spot instances can be persistent

openstack/network-2.tf
OVH requires port security to be enabled, but does not enable it by default.
=> Enable explictly port_security_enabled in network-2.tf for OpenStack

common/variables.tf
Creating a cluster with more than one proxy creates problem when using JupyterHub since each hub has its own database and configurable http proxy, resulting in users being forwarded to the wrong hub by the dns round robin and getting connection error.
=> Add validation on proxy and login tags in var.instances

docs/README.md, examples/openstack/main.tf, openstack/infrastructure.tf, openstack/versions.tf
Fix the issue where the image name in OpenStack is a moving target and examples can fall behind.
=> Allow openstack image to be a regular expression

CHANGELOG.md, aws/infrastructure.tf, azure/infrastructure.tf, common/configuration/main.tf, common/configuration/puppet.yaml, common/variables.tf, dns/cloudflare/main.tf, dns/cloudflare/variables.tf, dns/gcloud/main.tf, dns/gcloud/variables.tf, dns/record_generator/main.tf, docs/README.md, docs/design.md, gcp/infrastructure.tf, openstack/infrastructure.tf
This PR is meant to be merged in conjunction with the branch of the same name `includes` in puppet-magic_castle repo.
The PR introduces the following changes:
- Added `skip_upgrade` optional input variable to skip upgrading packages during cloud-init.
- Added `puppetfile` optional input variable to add modules to install or redefine the entire file if a forge command is provided.
- Changed the FQDN set by cloud-init from just the node name to node_name.int.domain_name. 
- Added variable vhosts to cloudflare and gcloud dns. This allows the definition of supplemental subdomains and vhost without much effort directly from the main.tf and hieradata.
=> Allow redefinition of Puppetfile and skipping upgrade

dns/acme/main.tf, dns/cloudflare/main.tf, dns/cloudflare/variables.tf, dns/cloudflare/versions.tf, dns/gcloud/main.tf, dns/gcloud/variables.tf, dns/gcloud/versions.tf, docs/README.md, examples/advanced/basic_puppet/openstack/main.tf, examples/advanced/k8s/openstack/main.tf, examples/advanced/lustre/openstack/main.tf, examples/advanced/spot_instances/aws/main.tf, examples/advanced/spot_instances/azure/main.tf, examples/advanced/spot_instances/gcp/main.tf, examples/aws/main.tf, examples/azure/main.tf, examples/gcp/main.tf, examples/openstack/main.tf, examples/ovh/main.tf
The generation of the wildcard certificate is no longer necessary as caddy handles certificate generation per vhost by itself and also handle renewal automatically. The wildcard generation was meant to be used when multiple proxy / jupyterhub would be used, but this has yet proven useful. Therefore, we are making the wildcard generation an exception instead of the general rule.
=> Make issuing wilcard ssl certificate optional

common/configuration/puppet.yaml
librarian-puppet will eventually by deprecated and r10k has proven to be way faster when installing modules.
The downsides is that Puppetfile will have to include all dependencies from now on since r10k does not track them.
=> Replace librarian-puppet by R10k

common/configuration/puppet.yaml
fadaray version >= 2.9 and faraday_net_http >= 3.1.0 released on January 9 2024 no longer support the Ruby version bundled with Puppet 7 - Ruby 2.8.
This PR fix the version of these packages.
=> Fix version of faraday* gems in cloud-init

common/variables.tf
close #269 
Simple validation to check if the `hierada` variable is valid YAML. This is the proposed solution for the issue.
It catches bad file formats, empty strings, and invalid strings.
=> Yaml validation on hierada

docs/README.md
This is really a small minimal example to receive Prometheus alerts on Slack. It doesn't show how to define new alerts to keep it small and not duplicate the original puppet-prometheus documentation.
If we want more complex examples, I would suggest to create a new documentation section ("Hieradata Advanced Examples") where we can show more complex hieradata use cases. We could also include [users disk quota](https://github.com/ComputeCanada/puppet-magic_castle/pull/308) examples in that section.
@cmd-ntrf  what do you think?
=> AlertManager documentation

common/configuration/puppet.yaml
Depends https://github.com/ComputeCanada/puppet-magic_castle/pull/331
This PR should be merge after the puppet one otherwise it will break EFA installation.
=> Remove efa driver installation from cloud-init (use puppet installation instead)

aws/infrastructure.tf, azure/infrastructure.tf, common/configuration/main.tf, common/configuration/puppet.yaml, common/provision/main.tf, common/variables.tf, docs/README.md, gcp/infrastructure.tf, openstack/infrastructure.tf
Close #287 
This PR allows for setting custom hieradata per group of instances sharing the same prefix.
It works by setting a new `prefix` fact on each instance. Then, all prefix hieradata are gathered in one file (`prefix.yaml`) and copied to `mgmt`. The hieradata are mapped based on the prefix and parsed accordingly by Puppet.
This approach differs from the task definition in the issue. Initially, the idea was to copy one file per prefix, but [Terraform provisioners don't support dynamic](https://github.com/hashicorp/terraform/issues/30225), and the number of files is only known at runtime.
See https://github.com/ComputeCanada/puppet-magic_castle/pull/324 for puppet logic
=> Hieradata per instances group

common/configuration/puppet.yaml
I was initially tying to add DEBUG log to journald. The logging is define by this [file](https://github.com/canonical/cloud-init/blob/90c15a60fbf035a9fbc2341834e1d6096e7889a9/config/cloud.cfg.d/05_logging.cfg#L60) and support sending log to `/dev/log` by default. Setting `log_cfgs: [ "*log_base", "*log_file", "*log_syslog" ]` will add the DEBUG log in journald, but unfortunately, it only apply after the first reboot. It would not work with the "mcspeed" project.
Instead, there is a parameter to change the log file permissions. I set the group to `systemd-journal` and should be accessible by vector.
=> Change permissions to /var/log/cloud-init.log

dns/cloudflare/main.tf, dns/cloudflare/versions.tf
The `value` field in the `cloudflare_record` is deprecated and stop working in v4.39.0 of Cloudflare terraform provider: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/record#value
From what I understand, this version was not suppose to stop supporting this field and can be considered a bug in the provider. But we should still switch to `content` because `value` is deprecated.
=> Update cloudflare record to support >=v4.39.0

.github/workflows/release.yaml, release.sh
close #319 
The file was not generated because the `terraform init` was failing due to minimum terraform version required. The CI was not falling on this error so, I added `set -e` to avoid the same issue in the future.
Should we set the terraform to latest in the CI?
=> Fix terraform lock file in release 

common/configuration/puppet.yaml
Fix an error in puppet server cloud-init about the gem "minitar" that could not be installed. The error was not critical as r10k was successfully installing its dependencies anyway, but the less error in logs the better.
=> Bump puppet and gem versions

azure/infrastructure.tf
Magic Castle documentation states the public_keys can be changed without impact on the cluster. For Azure, it was false as any change to public_keys would trigger a rebuild of all instances.
=> Add admin_ssh_key to ignore_changes list in Azure

common/configuration/puppet.yaml
This is to avoid issues with other puppet modules, such as duo-unix, which use augeas to configure sshd. augeas has issues when trying to add new directives if there are Match directives in the sshd_config file. 
This goes hand in hand with PR https://github.com/ComputeCanada/puppet-magic_castle/pull/416
=> Split sshd config so that Match directives are in their own files

docs/README.md
- Added pointers for configuring FreeIPA post-deployment using CLI.
- Fixed a reference link to a section
=> Added documentation for FreeIPA configuration

.github/workflows/trivy_scan.yaml, .gitignore, compose.sh
- scirelgar/magic_castle#1
- scirelgar/magic_castle#2
This new workflow configures [Trivy](https://trivy.dev/latest/), a static code analysis tool for IaC codebase and more. Trivy helps detect misconfigurations and vulnerabilities using the [Aqua Security vulnerability database](https://avd.aquasec.com/).
The `compose.sh` script creates temporary directories grouped by provider so that Trivy can scan them individually. This approach avoids duplication of scan results caused by symlinks present in the repository structure. These symlinks improve maintainability and release workflows but confuse the scan output if not handled properly.
Trivy scan results are exported in [SARIF format](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code …
=> Adding code scan (#3)

common/configuration/puppet.yaml
In combination with https://github.com/ComputeCanada/puppet-magic_castle/pull/434, it means we can now track Puppet agent metrics in Prometheus.
=> Enable puppet prometheus reporting

common/configuration/puppet.yaml.tftpl
> OpenVox started life as a Puppet™️ mirror by [Overlook InfraTech](https://overlookinfratech.com/downloads/) to continue providing community packages when Perforce discontinued public packaging efforts in late Fall of 2024.
https://voxpupuli.org/openvox/
=> Replace puppetlabs-puppet by OpenVox

common/configuration/puppet.yaml.tftpl
A few things were broken:
- The regex to retrieve the OS major version was working for only one digit.
- Bump the openvox server version. Previous version depended on an java rpm that is no available in EL10.
- Incus image for Rocky and AlmaLinux 10 come with `/etc/sshd/sshd_config` even if openssh-server is not installed. It needs to be deleted before installing the rpm otherwise sshd config is broken.
=> Fixes to be able to complete the puppet installation and configuration with EL10 images
